# This file imports the machine-specific hardware configuration
# from the backup location created during setup.
# 
# The actual hardware config is generated by NixOS and contains
# your specific filesystem UUIDs and hardware settings.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    /etc/nixos.backup/hardware-configuration.nix
  ];
}
